---
- hosts: app
  remote_user: deploy
  gather_facts: false

  vars:
    - web_root: /data/tomcat7/webapps
    - war_archive: ROOT.war

  vars_files:
    - vars.yml

  tasks:
    - name: Upload WAR to application server
      copy:
        src={{ war_archive }}
        dest={{ web_root }}/{{ war_archive | basename }}
        backup=true
        owner=deploy
        group=deploy
        mode=0644

    - name: Remove old application files
      file:
        name={{ web_root }}/{{ war_archive | regex_replace('\.([Ww][Aa][Rr])', '') }}
        state=absent

    - name: Restart Tomcat
      command: sudo /etc/init.d/tomcat7 restart
