---
- hosts: app
  remote_user: deploy
  gather_facts: false

  vars:
    - app_path: /data/tomcat7/webapps

  vars_prompt:
    - name: archive
      prompt: "Path to local WAR file (relative to playbook)"
      default: ./ROOT.war
      private: false

  tasks:
    - name: Upload WAR to application server
      copy:
        src={{ archive }}
        dest={{ app_path}}/{{ archive | basename }}
        backup=true
        owner=deploy
        group=deploy
        mode=0644

    - name: Remove old application files
      file:
        name={{ app_path }}/{{ archive | regex_replace('\.([Ww][Aa][Rr])', '') }}
        state=absent

    - name: Restart Tomcat
      command: sudo /etc/init.d/tomcat7 restart
